baseURL = "/"
languageCode = "en-us"
title = "Aashiyana of Pamela Santanu"
theme = "santm-bulma_v2"
[wordCount]
other = "{{ .WordCount }} words"
[params]
  author = "Santanu Misra"
  description = "Rumblings on life, travel or anything under sun"
  
    [[params.LeftMenu]]
    medium = "Facebook"
    icon = "fab fa-facebook-square"
    link = "https://www.facebook.com/santm"
  [[params.LeftMenu]]
    medium = "Instagram"
    icon = "fab fa-instagram-square"
    link = "https://www.instagram.com/s.a.n.t.m/"
  [[params.RightMenu]]
    medium = "Blog"
    icon = "fas fa-newspaper"
    link = "/blog"
  [[params.RightMenu]]
    medium = "Photos"
    icon = "fas fa-camera"
    link = "https://www.flickr.com/photos/santm/albums"
  [[params.RightMenu]]
    medium = "About"
    icon = "fas fa-user"
    link = "/about"
  [[params.RightMenu]]
    medium = "Contact"
    icon = "fas fa-id-card"
    link = "/contact"
  [[params.RightMenu]]
    medium = "Tags"
    icon = "fas fa-tags"
    link = "/tags"
[taxonomies]
    year = "year"
    month = "month"
    tags = "tags"
[permalinks]
    post = "/posts/:year/:month/:slug/"
    year = "/posts/:slug/"
    month = "/posts/:slug/"
